import turtle
t = turtle.Pen()
t.shape("blank")


def rechtecke():
    t.home()
    t.clear()
    t.pencolor("gray")
    t.pensize(2)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.up()
    t.goto(55, 55)
    t.down()
    t.forward(25)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(25)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.up()
    t.forward(200)
    t.down()


def herz():
    t.home()
    t.clear()
    t.pencolor("red")
    t.color("red")
    t.begin_fill()
    t.pensize(3)
    t.left(50)
    t.forward(133)
    t.circle(50, 200)
    t.right(140)
    t.circle(50, 200)
    t.forward(133)
    t.end_fill()
    t.up()
    t.forward(200)
    t.down()


def haus():
    t.home()
    t.clear()
    c = t.clone()
    t.pencolor("orange")
    c.pencolor("green")
    t.pensize(5)
    c.pensize(1)
    # haus
    t.up()
    c.up()
    t.forward(50)
    c.backward(250)
    t.down()
    c.down()
    t.forward(200)
    c.forward(200)
    t.left(90)
    c.left(90)
    t.forward(100)
    c.forward(100)
    t.left(90)
    c.left(90)
    t.forward(200)
    c.forward(200)
    t.left(90)
    c.left(90)
    t.forward(100)
    c.forward(100)
    t.left(180)
    c.left(180)
    t.forward(100)
    c.forward(100)
    # dach
    t.right(45)
    c.right(45)
    t.forward(142)
    c.forward(142)
    t.right(90)
    c.right(90)
    t.forward(142)
    c.forward(142)
    # tur
    t.up()
    c.up()
    t.right(45)
    c.right(45)
    t.forward(100)
    c.forward(100)
    t.right(90)
    c.right(90)
    t.forward(170)
    c.forward(170)
    t.right(90)
    c.right(90)
    t.down()
    c.down()
    t.forward(40)
    c.forward(40)
    t.right(90)
    c.right(90)
    t.forward(25)
    c.forward(25)
    t.right(90)
    c.right(90)
    t.forward(40)
    c.forward(40)
    t.left(180)
    c.left(180)
    t.forward(40)
    c.forward(40)
    t.right(90)
    c.right(90)
    # fenster
    t.up()
    c.up()
    t.forward(50)
    c.forward(50)
    t.down()
    c.down()
    for i in range(4):
        t.forward(30)
        c.forward(30)
        t.left(90)
        c.left(90)
    t.up()
    c.up()
    t.right(90)
    c.right(90)
    t.forward(200)
    c.forward(200)
    t.down()
    c.down()

def menu():
    print("[1] Option 1")
    print("[2] Option 2")
    print("[3] Option 3")
    print("[0] Option 0")


menu()
option = int(input("Enter your option: "))

while option != 0:
    if option == 1:
        rechtecke()
    elif option == 2:
        herz()
    elif option == 3:
        haus()
    else:
        print("invalid option ")
    menu()
    option = int(input("Enter your option: "))
print("Hope it was useful! Goodbye!")
